name: Engage
favicon: null
layout_spectrum: 0.6186860483139753
typography_spectrum: 0.07143504661507905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9880598126910627
  lightness: 0.60385014093481
  saturation: 0.43598343688063323
  rhythmicContrast: 0.7795381562318653
purpose: []
